component: express
name: fullstack-api
app: fullstack-serverless-db

inputs:
  src:
    src: ./
    exclude:
      - .env
  functionName: ${name}
  region: ${env:REGION}
  runtime: Nodejs10.15
  functionConf:
    timeout: 30
    vpcConfig:
      vpcId: ${output:${stage}:${app}:fullstack-vpc.vpcId}
      subnetId: ${output:${stage}:${app}:fullstack-vpc.subnetId}
    environment:
      variables:
        PG_CONNECT_STRING: ${output:${stage}:${app}:fullstack-db.private.connectionString}
  apigatewayConf:
    enableCORS: true
    protocols:
      - http
      - https
  # customDomain:
  #   - domain: test.chiro.work
  #     # 如要添加https，需先行在腾讯云-SSL证书进行认证获取cettificateId
  #     certificateId: fC8WFilQ
  #     protocols:
  #       - http
  #       - https
